config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'

  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :cases
  resources :news
  resources :forum_threads, except: [:edit, :update, :destroy]
  resources :lawyer_details, except: [:destroy]
  resources :rooms, only: [:show, :index] do
    resources :messages, only: [:create]
  end

  resources :lawyer_details, only: [:index, :show] do
    resources :reviews, only: [:create]
  end

  post '/users/hire', to: 'users#hire_lawyer', as: 'hire_lawyer'
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex') do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegalServices</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: grey !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
    display: flex;
      justify-content: flex-end
      }
    </style>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <div class="topnav">
        <a class="active", href="http://localhost:3000/">LEGAL SERVICES</a>
            <% if user_signed_in? && current_user.role == "lawyer" %>
              <%= link_to "ADD DETAILS", new_lawyer_detail_path , method: :new %>
              <%= link_to "ADD NEWS", new_news_path %>
              <%= link_to "NEWS", news_index_path %>
              <%= link_to "FORUM", new_forum_thread_path , method: :new%>
              <%= link_to "THREADS", forum_threads_path, method: :get %>
              <%= link_to "LAWYERS", lawyer_details_path, method: :get %>
               <a class="signout"><%= button_to "LOG OUT", destroy_user_session_path, method: :delete %></a>
              <% if current_user.image.attached? %>
                <%= link_to cases_path do %>
                  <%= image_tag(current_user.image, style: "display: inline-block; height:50px; width: 50px; border-radius: 50%;") %>
                <% end %>
              <% else %>
                <%= link_to cases_path do %>
                  <%= image_tag("default_profile.png", style: "display: inline-block; height:50px; width: 50px; border-radius: 50%;") %>
                <% end %>
              <% end %>
            <% else %>
              <% if user_signed_in? %>
              <%= link_to "NEWS", news_index_path %>
              <%= link_to "FORUM", new_forum_thread_path , method: :new%>
              <%= link_to "THREADS", forum_threads_path, method: :get %>
              <%= link_to "LAWYERS", lawyer_details_path, method: :get %>
              <a class="signout"><%= button_to "LOG OUT", destroy_user_session_path, method: :delete %>
              <% if current_user.image.attached? %>
                <%= link_to cases_path do %>
                  <%= image_tag(current_user.image, style: "display: inline-block; height:50px; width: 50px; border-radius: 50%;") %>
                <% end %>
              <% else %>
                <%= link_to cases_path do %>
                  <%= image_tag("default_profile.png", style: "display: inline-block; height:50px; width: 50px; border-radius: 50%;") %>
                <% end %>
              <% end %>
            </a>
            <% else %>
            <%= link_to "SIGN IN", new_user_session_path %>
            <% end %>
          <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/authorized_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unauthorized Access</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .container {
      background-color: #fff;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
    }

    h1 {
      color: #e74c3c;
      margin-bottom: 10px;
    }

    p {
      color: #333;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Unauthorized Access</h1>
    <p>Sorry, you do not have permission to access this page.</p>
  </div>
</body>
</html>